---
# tasks file for proyej.php
- name: Agregar el registro PPA para php
  apt_repository: repo='ppa:ondrej/php'
- name: Actualizar cache APT
  apt: update_cache=yes cache_valid_time=3600
- name: Instalar PHP
  apt: name={{item}} state=installed
  with_items:
  - php
  - php-fpm
  - php-mysql
  - php-xml
- name: Remover Apache
  apt: name=apache2 state=removed